---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web
  namespace: qos-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-java
  template:
    metadata:
      labels:
        app: web-java
    spec:
      containers:
      - name: webapp
        image: cruelgangsta/jdkmavengit:47
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
        readinessProbe:
          httpGet:
            path: /sum?a=1&b=1
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /sum?a=1&b=1
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      nodeSelector:
        kubernetes.io/hostname: slavekub30
---
apiVersion: v1
kind: Service
metadata:
  name: java-web-svc
  namespace: qos-example
spec:
  type: NodePort
  selector:
    app: web-java
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30003
