---
apiVersion: v1
kind: Namespace
metadata:
  name: qos-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web
  namespace: qos-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-java
  template:
    metadata:
      labels:
        app: web-java
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disks
                operator: In
                values:
                - ssd
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web
            topologyKey: disks
      containers:
      - name: webapp
        image: cruelgangsta/jdkmavengit:47
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
        readinessProbe:
          httpGet:
            path: /sum?a=1&b=1
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /sum?a=1&b=1
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: java-web-svc
  namespace: qos-example
spec:
  type: NodePort
  selector:
    app: web-java
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30003
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-web
  labels:
    app: web
  namespace: qos-example
spec:
  containers:
  - name: web-app
    image: nginx